In [1]:
import numpy as np

In [6]:
asd  = np.array([5,6,1,2,3,4])

In [7]:
asd

array([5, 6, 1, 2, 3, 4])

In [24]:
asd.sort()

In [25]:
asd

array([1, 2, 3, 4, 5, 6])

In [26]:
asdf = np.flip(asd)

In [27]:
asdf


array([6, 5, 4, 3, 2, 1])

In [28]:
asd

array([1, 2, 3, 4, 5, 6])

In [30]:
np.argmax(asd)

5

In [31]:
np.argsort(asd)

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [32]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
print(array1)

[1 2 3]


In [33]:
print(array2)

[4 5 6]


In [34]:
array1 +array2

array([5, 7, 9])

In [35]:
list1 = [1,2,3]
list2 = [4,5,6]

In [36]:
list1+list2

[1, 2, 3, 4, 5, 6]

In [37]:
array1

array([1, 2, 3])

In [38]:
array1[::-1]

array([3, 2, 1])

In [39]:
list2

[4, 5, 6]

In [42]:
list(reversed(list2))

[6, 5, 4]

In [43]:
fg  = np.array([55,11,22,44,66])

In [44]:
fg

array([55, 11, 22, 44, 66])

In [46]:
np.flipud(fg) == fg[::-1]

array([ True,  True,  True,  True,  True])

In [58]:
fg  = np.array([[55,11,22,44,66],[5,1,2,4,6],[0,0,0,0,0]])

In [59]:
fg

array([[55, 11, 22, 44, 66],
       [ 5,  1,  2,  4,  6],
       [ 0,  0,  0,  0,  0]])

In [50]:
type(fg)

numpy.ndarray

In [51]:
fg.shape

(2, 5)

In [61]:
np.flip(fg)

array([[ 0,  0,  0,  0,  0],
       [ 6,  4,  2,  1,  5],
       [66, 44, 22, 11, 55]])

In [60]:
np.flipud(fg)

array([[ 0,  0,  0,  0,  0],
       [ 5,  1,  2,  4,  6],
       [55, 11, 22, 44, 66]])

In [62]:
fg

array([[55, 11, 22, 44, 66],
       [ 5,  1,  2,  4,  6],
       [ 0,  0,  0,  0,  0]])

In [63]:
fg[::-1]

array([[ 0,  0,  0,  0,  0],
       [ 5,  1,  2,  4,  6],
       [55, 11, 22, 44, 66]])

In [64]:
import array

In [68]:
as1 = array.array('i',[1,2,3])

In [66]:
import array
 
#The original array
new_arr=array.array('i',[2,4,6,8,10,12])
print("Original Array is :",new_arr)
 
#reversing using reverse()
new_arr.reverse()
print("Reversed Array:",new_arr)

Original Array is : array('i', [2, 4, 6, 8, 10, 12])
Reversed Array: array('i', [12, 10, 8, 6, 4, 2])


In [69]:
as1

array('i', [1, 2, 3])

In [70]:
as2 = array.array('i',[11,2,3])

In [71]:
as2

array('i', [11, 2, 3])

In [72]:
as1+as2

array('i', [1, 2, 3, 11, 2, 3])

In [73]:
as1-as2

TypeError: unsupported operand type(s) for -: 'array.array' and 'array.array'

In [74]:
as1*2

array('i', [1, 2, 3, 1, 2, 3])

In [75]:
asd1 = 'mayuri'

In [76]:
asd1

'mayuri'

In [77]:
asd*2

array([ 2,  4,  6,  8, 10, 12])

In [78]:
asd1*2

'mayurimayuri'

In [79]:
asd1+asd1

'mayurimayuri'