In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [3]:
a not in b

True

In [6]:
c = np.array(list(filter(lambda x: x not in b, a)))

In [7]:
c

array([1, 2, 3, 4])

In [8]:
np.intersect1d(a,b)

array([5])

In [9]:
c1 = np.array(list(filter(lambda x: x in b , a)))

In [10]:
c1

array([5])

In [11]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
import time

In [16]:
l = time.localtime()

In [20]:
time.strftime('%Y',l)

'2021'

In [28]:
n= 5
for i in range(n):
    for j in range(i):
        print('*', end = '')
    print(' ')
for i in range(5,-1):
    for j in range(i):
        print('*', end = '')
    print(' ')

 
* 
** 
*** 
**** 


In [31]:
for i in range(n,0,-1):
    for j in range(i):
        print('*', end = '')
    print(' ')

***** 
**** 
*** 
** 
* 


In [40]:
n = int(input('enter the range:'))
list1= []
for i in range(2,n):
    for temp in range(2,i):
        if i%temp == 0:
            break
        else:
            list1.append(i)
print(set(list1))

enter the range:21
{3, 5, 7, 9, 11, 13, 15, 17, 19}


In [42]:
def func1(a,b,c):
    
    if (a**2 + b**2) == c**2:
        return "It is a right angle triangle"
    elif (b**2 + c**2) == a**2:
        return "It is a right angle triangle"
    elif (c**2 + a**2) == b**2:
        return "It is a right angle triangle"
    else:
        return "NOooo"
        
        

In [41]:
3,4 >5

(3, False)

In [43]:
func1(3,4,5)

'It is a right angle triangle'

In [52]:
list1 = []
def fibo1(n):
    a,b = 0,1
    while b <= n:
        list1.append(b)
        
        a,b = b,a+b
    return list1
       

In [53]:
fibo1(10)

[1, 1, 2, 3, 5, 8]

In [55]:
def func1(a,b):
    if b ==0:
        return 1
    else:
        return a**b

In [57]:
func1(2,3)

8

In [64]:
list1 = list(reversed('mayu'))

In [62]:
'mayu'.Reverse()

AttributeError: 'str' object has no attribute 'Reverse'

In [63]:
l = 'mayuri mhetre'
print(l[::-1])

ertehm iruyam


In [65]:
list1

['u', 'y', 'a', 'm']

In [67]:
''.join(list1)

'uyam'

In [69]:
def func_str(str1):
    return ''.join(list(reversed(str1)))

In [70]:
func_str('hi hello')

'olleh ih'

In [74]:
def func2(n):
    a = 0
    for i in range(1,n+1):
        a = a+ i**3
    return a
    

In [75]:
func2(5)

225

In [73]:
1+8+27+64+125

225

In [83]:
def func(list1):
    a = len(list1)
    list1[0] , list1[a-1] = list1[a-1],list1[0]
    return list1
     

In [84]:
func([i for i in range(5)])

[4, 1, 2, 3, 0]

In [78]:
len([i for i in range(5)])

5

In [79]:
list1= [i for i in range(5)]

In [80]:
list1

[0, 1, 2, 3, 4]

In [82]:
list1[5]

IndexError: list index out of range

In [85]:
str1 = 'mayuri_mhetre_python'

In [87]:
str1

'mayuri_mhetre_python'

In [91]:
str1.replace('_',' ').capitalize().replace(' ','')

'Mayurimhetrepython'

In [92]:
def pali(str):
    if str  == ''.join(list(reversed(str))):
        return "It is a palindrom"
    else:
        return "NOOOOO"

In [93]:
pali('mayuri')

'NOOOOO'

In [94]:
pali('nitin')

'It is a palindrom'

In [100]:
list1 = [i for i in range(1,6)]

In [101]:
sum(list1)

15

In [102]:
list1

[1, 2, 3, 4, 5]

In [103]:
5*4

20